@startuml flashyRestAPIClassDiagram
package rest-API {
    class MainController {
        - final userService: UserService
        - final cardService: CardService

        + MainController(UserService userService, CardService cardService)
        + verifyLogin(@RequestParam String username, @RequestParam String password): ResponseEntity<String>
        + registerUser(@RequestParam String username, @RequestParam String password, @RequestParam String email): ResponseEntity<String>
        + getMySets(): ResponseEntity<ArrayList<Set>>
        + getMyFavorites(): ResponseEntity<ArrayList<Set>>
        + searchFor(@PathVariable ("searchword") String searchWord):  ResponseEntity<ArrayList<Set>>
        + getProfileInfo(): ResponseEntity<ArrayList<String>>
    }
    class CardService {
        - final dataSource: DataSource

        +  CardService(DataSource dataSource)
        + searchEngine(String searchWord): ArrayList<Set>
    }
    class UserService {
        - loggedIn: User
        - final dataSource: DataSource

        + UserService(DataSource dataSource)
        + verifyLogIn(String username, String psw): boolean 
        + registerUser(String username, String psw, String email): boolean 
        + findSetByID(ArrayList<Set> sets, int i): Set
        + getMySets(): ArrayList<Set>
        + getFavorites(): ArrayList<Set>
    }
}
@enduml
