@startuml flashyClassDiagram

package flashy {
    class user {
        - USERID: String
        - username: String
        - PASSWORD: String
        - EMAIL: String
        - isAdmin: boolean

        + user(string username, String password, String email, boolean password)
        

    }
    class card {
        
    }
    class set {

    }
    
}
@enduml 
